spring:
  datasource:
    url:
    driver-class-name:

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.type.descriptor.sql: trace
