spring:
  h2:
    console:
      enabled: true
      path: /h2-console


  datasource:
    url: jdbc:h2:mem:~/mukitListApplication
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    defer-datasource-initialization: true # (2.5~) Hibernate 초기화 이후 data.sql 실행
logging:
  level:
    org.hibernate.SQL: debug

    org.hibernate.type.descriptor.sql: trace

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha

security:
  jwt:
    secret-key: "!@#$%ASDFZXCVBASDFZXCVBASDFZXCVBASDFZXCVBASDFZXCVBASDFZXCVBASDFZXCVBASDFZXCVBASDFZXCVB"
    expiration: 360000
---
spring:
  config:
    activate:
      on-profile: test
  sql:
    init:
      mode: never

---
spring:
  config:
    activate:
      on-profile: dev
  sql:
    init:
      mode: never

